### ISSUE TITLE
Material Design Icons cannot be used with Dart SDK 2.1.0

### ISSUE THREAD

**Issue by ekigamba** [ziofat/material_design_icons_flutter#1]
I get the following error:

```
Because *app_name depends on material_design_icons_flutter >=2.3.50 which requires SDK version >=1.19.0 <2.0.0, version solving failed.
pub upgrade failed (1)
```

Could you kindly update the dependencies so that it can work with the following?

```
Flutter 0.6.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 9299c02cf7 (2 weeks ago) • 2018-08-16 00:35:12 +0200
Engine • revision e3687f70c7
Tools • Dart 2.1.0-dev.0.0.flutter-be6309690f
```

**Comment by arthurgustin** [comment]
Same here:
`Because material_design_icons_flutter 2.3.50 requires SDK version >=1.19.0 <2.0.0 and no versions of material_design_icons_flutter match >2.3.50 <3.0.0, material_design_icons_flutter ^2.3.50 is forbidden.
`
