### ISSUE TITLE
support all icon from mdi like power-socket-eu

### ISSUE THREAD

**Issue by tuanha2000vn** [ziofat/material_design_icons_flutter#12]
When I tried a few non-standard Mdi Icon like MdiIcons.fromString('power-socket-eu') it can't display on flutter ui, can you make it work?

https://iconify.design/icon-sets/mdi/power-socket-eu.html

Thank you, love the package.

**Comment by ziofat** [comment]
Try `MdiIcons.fromString('powerSocketEu')` instead.
I believe that dash style icon name should be supported soon, stay tuned.
Meanwhile, I still suggest using `MdiIcons.powerSocketEu` so tree-shaking will eliminate unused icons.

**Comment by ziofat** [comment]
fixed in b5cc4f7fccf5cb30045096f188a124be3d6fd4a2, published in `3.3.4595`

**Comment by tuanha2000vn** [comment]
Thank you  ziof
