### ISSUE TITLE
no support for everything

### ISSUE THREAD

**Issue by reals79** [ziofat/material_design_icons_flutter#13]
I understand that not all icons are in the package?

For example: handshake
not found

**Comment by ziofat** [comment]
It seems `handshake` was introduced a week ago, and will be released in 4.6.95.
https://github.com/Templarian/MaterialDesign/commit/088389eebbd06fbc4977431375cc1465b46b2e3e

I am pretty sure you can not find this icon in official npm mdi lib either. Stay tuned, I will update as soon as they release a new version.

**Comment by reals79** [comment]
okay.
Thanks!

**Comment by ziofat** [comment]
`handshake` is shipped with latest version.
