### ISSUE TITLE
`account-tie-voice` is missing. 

### ISSUE THREAD

**Issue by naco-siren** [ziofat/material_design_icons_flutter#18]
And wondering how frequently is this repo being updated

**Comment by ziofat** [comment]
This package will run update script once a week. There is a pipeline doing so now. Once there is release, I will get an email notification.

This package rely on official font file, as flutter's svg support was poor when I composed this package. Thus not all icons in [materialdesignicons.com](materialdesignicons.com) is bundled in this package. MDI has its own release pace and you cannot find this `account-tie-voice` icon in official npm package `@mdi/js` either.

I believe this icon should be released soon in mdi. And I will update this package as soon as possible when I got notification.
