### ISSUE TITLE
All icons showing up as question mark in box

### ISSUE THREAD

**Issue by emptyopen** [ziofat/material_design_icons_flutter#19]
I've tried various icons, all of them show up like:
![image](https://user-images.githubusercontent.com/18575100/75000383-08626780-5413-11ea-9c15-06abf41c9566.png)

No errors, just the question mark. 

Copied the example in README exactly.

**Comment by emptyopen** [comment]
Resolved by closing the app in the emulator and restarting (I think this issue occurs whenever you add a new library).

**Comment by ziofat** [comment]
Well, glad you resolved it. This library introduced a font file in your application, which might need to be load on first run.
