### ISSUE TITLE
Import not working - Target of URI doesn't exist

### ISSUE THREAD

**Issue by KanivaTimber** [ziofat/material_design_icons_flutter#2]
Hello,

When trying to import the library **package:material_design_icons_flutter/material_design_icons_flutter.dart** into my dart file it says that the "Target of URI doesn't exist".
- I added the **material_design_icons_flutter: 2.7.94** dependency in my pubspec.yaml
- Ran "flutter packages get" and had an exit code 0
- Currently have Flutter v0.8.2

Thanks in advanced!

**Comment by ziofat** [comment]
Try restarting the IDE might solve this.

If not, `pub get` might be helpful.

**Comment by KanivaTimber** [comment]
Seemed to be to the IDE (Visual Studio Code). After restarting it, it recognized it. Thank you!
