### ISSUE TITLE
Breaking changes in 3.4.5045

### ISSUE THREAD

**Issue by Niek** [ziofat/material_design_icons_flutter#20]
This commit broke our app: https://github.com/ziofat/material_design_icons_flutter/commit/d1899c950d4082f122cdcebc575ae7da04c00532

Lots of icons have different identifiers, for example ``settingsOutline`` is now ``cog``. In my opinion this should be a major version bump to 4.x.

**Comment by ziofat** [comment]
Material design icons never respect the semver though, their version is the
number of icons they have. Name changing happened in almost every releasea
of the Material design icons. Using a fix version is highly recommend.

I will look into it, trying to find a way to make alias available for this
package.

**Comment by ziofat** [comment]
Well, now I noticed there is a breaking change list in MDI repo. https://github.com/Templarian/MaterialDesign/issues/4901

I will see what I can do with it. You're right, it should be a major release.

**Comment by ziofat** [comment]
Fixed this with `3.4.5045+1`, which use a custom build font containing removed and renamed icons.
