### ISSUE TITLE
Mdi-blank not implemented

### ISSUE THREAD

**Issue by alguintu** [ziofat/material_design_icons_flutter#23]
Why is mdi-blank not implemented?
It has been with MDI since version 1.7.
Please include it as there are some good use cases for it.
Thanks.

**Comment by ziofat** [comment]
It seems neither implemented in MDI js distribution or svg distribution. `mdi-blank` is more like a random icon with a `visibility: hidden;` in css.

Since it is not an icon, this flutter version may not implement it. A property to make variation to an icon is a more sensible approach.

**Comment by alguintu** [comment]
Hi. Thanks for the response. Figured to just use a opacity with a random icon.
