### ISSUE TITLE
Can't find store-remove

### ISSUE THREAD

**Issue by rubgithub** [ziofat/material_design_icons_flutter#29]
I Can't find store-remove icon, I'm using `4.0.5755`

**Comment by ItsJimi** [comment]
Hello, found it in [/lib/material_design_icons_flutter.dart#L5014](https://github.com/ziofat/material_design_icons_flutter/blob/master/lib/material_design_icons_flutter.dart#L5014). I think it should be available.

**Comment by ziofat** [comment]
I can confirm it exists in example app.

**Comment by rubgithub** [comment]
Thanks, my mistake.
