### ISSUE TITLE
[Q] materialdesignicons.com is down. Any alternatives?

### ISSUE THREAD

**Issue by henry2man** [ziofat/material_design_icons_flutter#30]
Hi. It looks that [materialdesignicons.com](https://materialdesignicons.com) is down. Is there any chances to browse icons in another place? Thanks.

**Comment by ziofat** [comment]
I will upload example app in apk mode from next release.

**Comment by henry2man** [comment]
Since there is a map with all the icons in the code, wouldn't it be easier to iterate over that map and create a single HTML page with all the icons and upload it in the release? I have no experience with web Flutter but it should not be difficult ... It could also be uploaded in GitHub Pages

**Comment by henry2man** [comment]
(Closed by mistake) 😓

**Comment by ziofat** [comment]
I have uploaded a web application build with [flutter web](https://ziofat.github.io/material_design_icons_flutter/), which is from the `example` project.

**Comment by henry2man** [comment]
> I have uploaded a web application build with [flutter web](https://ziofat.github.io/material_design_icons_flutter/), which is from the `example` project.

Simply AMAZING! Well done 👏🏻
