### ISSUE TITLE
Add Support for Flutter 2.0 with Null Safety

### ISSUE THREAD

**Issue by AathifMahir** [ziofat/material_design_icons_flutter#32]
Most of the users were started updating to Flutter 2.0 with Null Safety, unfortunately this package not yet reached null safety version. Please have us null safety version of this package as soon as possible.

Thanks for contributing!

**Comment by SaeDocas** [comment]
I would like to emphasize the importance of this too,do let me know if you need any help @maintainers

**Comment by ziofat** [comment]
PR #31 has been merged, I am doing some test with Flutter 2.0. However, null safety support is a breaking change for this package, while we are also expecting another breaking change from [MDI](https://github.com/Templarian/MaterialDesign). So I am considering if I should hold this version.

**Comment by ziofat** [comment]
For flutter 2.0, I may going to publish a release candidate version. Please note there is another breaking change coming.

**Comment by ziofat** [comment]
Closed with [5.0.5955-rc.1](https://pub.dev/packages/material_design_icons_flutter/versions/5.0.5955-rc.1)
