### ISSUE TITLE
Cant seem to find icon

### ISSUE THREAD

**Issue by febg11** [ziofat/material_design_icons_flutter#33]
Hi 

I was hoping to use this icon 

https://material.io/resources/icons/?search=device&icon=remember_me&style=baseline

But i cant seem to find it as an option on the current version

Thanks

**Comment by ziofat** [comment]
Hi, this package is an implementation of [MDI](https://materialdesignicons.com/), which is a community driven icon set. It includes most of official material icons but may miss some new ones. We will not implement any other icons not provided by mdi.

Unfortunately, this icon is list in neither [Google's official material icons repo](https://github.com/google/material-design-icons) nor [flutter Icons class documentation](https://api.flutter.dev/flutter/material/Icons-class.html). It seems you can only use this icon by importing its raw font file in your project.

You can file an issue in [Google's official material icons repo](https://github.com/google/material-design-icons) or [MDI](https://github.com/Templarian/MaterialDesign). Once they resolve this issue, this icon will also come to this package.
