### ISSUE TITLE
Strange version number 

### ISSUE THREAD

**Issue by guyluz11** [ziofat/material_design_icons_flutter#44]
Why does this package version is "5.0.6595"?.

It will be more professional to just increase the version to 5.1.0 wouldn't it?

**Comment by ItsJimi** [comment]
> Why does this package version is "5.0.6595"?.

The patch number refer to the material design icons version. In our case, `6595` to `6.5.95`.

**Comment by guyluz11** [comment]
So are we going to change it from `5.0.5695` to `6.5.95`?

**Comment by ItsJimi** [comment]
No, the major and minor parts are dedicated to the flutter package.
For exemple if you fix an issue but the material design icons font doesn't change, the new version of flutter package will be `5.1.6595`.

**Comment by guyluz11** [comment]
Thanks for the explanation.
