### ISSUE TITLE
Update to 6.6.96

### ISSUE THREAD

**Issue by ViliusP** [ziofat/material_design_icons_flutter#46]
Current version is based on Material Design Icons 6.5.95.
Latest Material Design Icons version is 6.6.96.

Could you update this package to the latest version?

**Comment by mauriziopinotti** [comment]
@ViliusP I've created a PR for version 6.7.96: #47 

Meanwhile, you can use this to have latest icons:

```yaml
  material_design_icons_flutter:
    git: https://github.com/easyhour/material_design_icons_flutter
```
