### ISSUE TITLE
Missing and wrong icons?

### ISSUE THREAD

**Issue by rgbinnovation** [ziofat/material_design_icons_flutter#48]
Hi, any plans to address missing and wrong icons? For example, the GROUP icon is supposed to show to people but shows a "select" icon, the construction and handyman icons are missing, and so on.

**Comment by ziofat** [comment]
All icons are based on https://materialdesignicons.com/, not Google's official material design icons.

Google's material design may introduce new icons which have conflict name with community version. Some of them were renamed in [MDI v7](https://github.com/Templarian/MaterialDesign/issues/6504), which will be update soon in this package.

This will be a constant gap when you trying to use offcial icons with same name. MDI is not an extension of Google's official material design icons, it is another version of it.

The `group` icon was named `account-multiple` in MDI, `construction` and `handyman` are pretty new. They have not yet been imported in MDI.
