### ISSUE TITLE
It would be nice to get the icon by string for late binding

### ISSUE THREAD

**Issue by ride4sun** [ziofat/material_design_icons_flutter#5]
Hello, thank you for this great package. 
I using late binding and would like to define Icons by there name like MdiIcons('sword').
That would allow me to define the icons in the domain without the reference of the package and I could create the UI dynamically in run-time.

**Comment by ziofat** [comment]
That is a great idea, I will try this in days.

**Comment by ride4sun** [comment]
@ziofat I was just wonrdering if you found the time to work on it. Is there something I can do?

**Comment by ziofat** [comment]
@ride4sun Hi, I have published a new version of this package. Check readme to see is that satisfied you.

**Comment by ride4sun** [comment]
@ziofat
Thank u. I will try it in the next few day and let u know. Great work.

**Comment by ride4sun** [comment]
@ziofat I think a static method would look better like:

`MDiIcons.fromString() `

instead of
 
```
ListTile(
                  leading: Icon(MdiIcons()[bloc.iconName]),
                  title: _buildValueDisplay(context, bloc),
                )
```

everything else is static and `MdiIcons()[bloc.iconName]` would be the only place where you would create an instance.

**Comment by ziofat** [comment]
I think you are right. I didn't put consideration in this.

**Comment by miguelangel-nubla** [comment]
Keep in mind that It is still useful to have a map that can be iterated to list or dynamically search icons by text.

In that regard, would it be possible to include the description and aliases as shown on the web page in a similar way?
That would enable users to build icon pickers.

**Comment by ziofat** [comment]
@miguelangel-nubla I do know that aliases exist but they can not be used to access icon in material-design-icon.
I can try to add alias support in example.

**Comment by ride4sun** [comment]
There could be another static which could returns the Iterator.

**Comment by ziofat** [comment]
closing this with 3.2.3595.
