### ISSUE TITLE
Is that possible to use this package somehow in flutter_web?

### ISSUE THREAD

**Issue by sgon00** [ziofat/material_design_icons_flutter#8]
After reading https://github.com/flutter/flutter_web/tree/master/examples/gallery/web/assets, I am not quite sure what to do and if it's possible to use this package somehow in flutter_web. Thanks a lot.

Edited: by reading this [commit](https://github.com/flutter/flutter/commit/4d3b51e28435446db849819ec98099cc51be070a), maybe flutter_web will be merged to flutter soon...

**Comment by ziofat** [comment]
That's correct, flutter_web will eventually be merged to flutter.

Currently you cannot use this package in flutter_web because as now flutter_web does not have a plugin system.

Check the [FAQ](https://github.com/flutter/flutter_web/commit/acf4aae2a60ef2c1df80bb05873401d83475d52b) in flutter_web for further explanation.

**Comment by sgon00** [comment]
Thanks a lot for the reply. The FAQ was not present at the time I filed this question. Hopefully flutter_web can be merged to flutter in a month. (Btw, your Chinese name surprised me when I read my notification email. ^_^ 有个性。)

**Comment by sgon00** [comment]
Dear sir, now flutter_web is kinda merged to flutter. Refer to this wiki https://github.com/flutter/flutter/wiki/Building-a-web-application-with-Flutter . But this icon plugin still does not work. Do you have any ideas how to make it work? The default Icons package is working though, so I think somehow, this package should work too with proper configuration. Thanks a lot.

**Comment by sgon00** [comment]
Please ignore my last comment. That was a bug. I filed it at flutter issue #39486 and it's fixed now. Thus, this package works in flutter_web now.

**Comment by ziofat** [comment]
@sgon00 Sure, that is how I found it as well.
