### ISSUE TITLE
Can you please update the icons when you have time?

### ISSUE THREAD

**Issue by sgon00** [ziofat/material_design_icons_flutter#9]
Hi, I found there are some icons that I want to use in materialdesignicons.com missing from this package. Can you please update the icons when you have time? Thank you very much for your hard work.

**Comment by ziofat** [comment]
Sure. Sorry for the delay.
The latest version have been published.

**Comment by sgon00** [comment]
@ziofat thanks a lot for the quick update. Just one more question, I have updated to 3.2.3695 but why can't I find file-document-box-plus-outline icon? Thanks.

**Comment by ziofat** [comment]
This plugin is built based on the webfont of mdi. The icon you ask was introduced at Apr 28, 2019, which is later than the latest mdi release (at Apr 15). I think this icon will be included at next release.

**Comment by sgon00** [comment]
@ziofat ok, got it. Thank you very much for the explanation and update again. 👍😀
